# Generated by Django 2.2.1 on 2019-09-06 18:52

from django.db import migrations

def categories_suggestions(apps, schema_editor):
    #Gets model from the app to make sure it exists
    Category = apps.get_model('TravelogueApp', 'Category')
    # Creates list of suggested categories to draw from
    Suggestions = ('Food','Scenery','Night Life','Travel')
    #save suggestions to the database
    for item in Suggestions:
        this = Category()
        this.name = item
        this.save()

class Migration(migrations.Migration):

    dependencies = [
        ('TravelogueApp', '0003_remove_post_slug'),
    ]

    operations = [
        migrations.RunPython(categories_suggestions),
    ]
